### ISSUE TITLE
Style mismatch

### ISSUE THREAD

**Issue by theoklink** [maxmpz/powerampapi#14]
<item name="com.maxmpz.audioplayer:colorBgPrimary">@color/transparent</item>

This is the background for Library Album, Track info etc BUT ALSO for Menus when selecting in library or Track Menu so you cannot read the menus.

in the style Base_ActivityTheme_Default.

**Comment by theoklink** [comment]
Style to apply corner radius for Artists in Library view missing? 
		<item name="cornerRadius">?corners_aa_tracks</item>
		<item name="cornerRadius2">?corners_aa_albums</item>
		<item name="cornerRadius3">?corners_aa_other</item>
The albumart does not change from "round" so I suspect  corners_aa_other is not applied.

**Comment by maxmpz** [comment]
Re: @color/transparent
I can see it's used only for window backgrounds, and indeed we should have it there, as main activity background is transparent as Milk GL surface is always on background, and for dialogs, custom frame is drawn.

What exactly menus do you mean? The popup menus shown on three-dots button? 
For these, colors are defined via:
styles-item.xml => ItemTrack => android:background => @drawable/item_bg => there are different backgrounds per different levels (item use cases).

**Comment by maxmpz** [comment]
Re: Artists radiuses defined by:
styles-item.xml => ItemTrackAAImage (and all ItemTrackAAImage_scene_* styles) => cornerRadius3

cornerRadius3 can be different in different scenes, but by default it's bound to:
?corners_aa_other, ?corners_aa_other_zoomed, ?corners_aa_other_grid

Check styles-item.xml around ItemTrackAAImage and ItemTrackAAImage_scene_* styles for details looking to cornerRadius3.

**Comment by theoklink** [comment]
Re@color/transparent
I noticed I missed the most imporant part
<item name="com.maxmpz.audioplayer:colorBgPrimary">@color/transparent</item>
Yes, the 3 dots popup menus and when selecting say an album in library view, the menu showing from the bottom.
I may be missing something here but it seems to me odd that menus are affected in this way as I view them as a separate entity to backgound on text labels.
I understand that it can be overwritten but I am in the first instance trying to work at theme level

**Comment by theoklink** [comment]
I noticed that the < item code etc keeps disappearing
It concerns colorBgPrimary﻿ though

**Comment by gcantoni** [comment]
@theoklink it's ok for me

**Comment by theoklink** [comment]
I think I need to understand developing skins a lot better first. I encountered what were in my view inconsistencies but perhaps I am barking up the wrong tree :) Thanks for the responses though

**Comment by maxmpz** [comment]
Re: menu background (menu is item itself) defined by:
(top attribute) ItemTrack => @style/ItemTrack => android:background => @drawable/item_bg => ITEM_BG_LEVEL_POPUP => colorBgPrimary
