### ISSUE TITLE
Transparent Theme

### ISSUE THREAD

**Issue by gcantoni** [maxmpz/powerampapi#15]
Hey Max,
Any suggestion for making this background transparent? Thanks!

https://imgur.com/a/EpqLkkD

**Comment by maxmpz** [comment]
Hi,
not sure what background you exactly mean, but if you want to change global list background to blurred one, you can override **listMilkMode** attribute to "listHeader".

You can do this the same way as "No Blur" option is implemented for SampleSkinAAA.
Search for SampleSkinAAA_noAABlur_TopListWidget style in sample_skin_aaa_styles.xml - it redefines it to none there, you need listHeader.

Note that listHeader options is not well tested as it's not in default skins, but if any issues let me know.
