### ISSUE TITLE
Play filtered option

### ISSUE THREAD

**Issue by wlimqtis101** [maxmpz/powerampapi#22]
After realize of the app with this beautiful design the option "play filtered" had disappeared. This feature was VERY userful and sometimes I want to install previous version just for this. I think a lot of people used this everyday.

**Comment by maxmpz** [comment]
You can request features here: https://forum.powerampapp.com/forum/4-feature-requests/

As for filtered playback, this migrated to Search, which can play (with > in header) just the results found.
