### ISSUE TITLE
Poweramp Skin transparency not working

### ISSUE THREAD

**Issue by gcantoni** [maxmpz/powerampapi#23]
Hey Maxim!

I'm facing an issue when making a full transparent skin.

Basically everything is transparent as it should be, except the main screen. Why?

I have used all available attributes for transparency offered by Android, and by using this in a normal application coded, the transparency works.

Could you please help? thank you

`<style name="oxygen_transparent" parent="com.maxmpz.audioplayer:style/Base_ActivityTheme_Black">
    <item name="android:windowBackground">@android:color/transparent</item>
    <item name="android:colorBackgroundCacheHint">@null</item>
    <item name="android:windowShowWallpaper">true</item>
    <item name="android:windowTranslucentNavigation">true</item>
    <item name="android:windowTranslucentStatus">true</item>
    <item name="android:windowContentOverlay">@null</item>
    <item name="android:windowNoTitle">true</item>
    <item name="android:backgroundDimEnabled">false</item>
    <item name="android:windowIsTranslucent">true</item>
    <item name="android:windowAnimationStyle">@android:style/Animation.Translucent</item>`

**Comment by gcantoni** [comment]
Attribute `android:windowShowWallpaper` should make the main screen transparent and the wallpaper visible but for some reason it doesn't ( only in PowerAmp ).

**Comment by maxmpz** [comment]
It's already transparent as drawing extra background slightly reduced drawing performance (see around line 88 in default-styles.xml). Poweramp uses Open GL surface over whole area to show blurred album art, visualizations, and backgrounds (activity_list_fast.xml line 56 <com.maxmpz.widget.player.MilkWidget...)

**Comment by m-i-n-a-r** [comment]
So basically this means that a transparent or semi-transparent skin is not possible, am i right? And disabling the milkmode via styles won't do the trick i guess.

**Comment by maxmpz** [comment]
It's possible
- add new option in your skins.xml, for example
```
		<option
			key="trans_bg_main"
			name="@string/skin_trans_bg_main"
			summary="@string/skin_summary_trans_bg_main"
			overlapStyle="@style/SampleSkin_transBgMain"
			checkedByDefault="false"
		/>
```
- add appropriate style to override TopMilk and hide it completely:
```
	<style name="SampleSkin_transBgMain">
		<item name="com.maxmpz.audioplayer:TopMilk">@style/SampleSkin_transBgMain_TopMilk</item>
		<item name="android:windowShowWallpaper">true</item>
		<item name="android:windowBackground">@android:color/transparent</item>
	</style>

	<style name="SampleSkin_transBgMain_TopMilk" parent="@com.maxmpz.audioplayer:style/TopMilk">
		<item name="android:visibility">gone</item>
	</style>

```

Note that this replaces main UI, lists, and equalizer background to wallpaper, thus, some elements/text may be not readable/visible depending on actual wallpaper image.

**Comment by gcantoni** [comment]
hi @maxmpz , your solution is partially working. poweramp gets most of its UI broken.

**Comment by gcantoni** [comment]
@maxmpz here there is how the UI works with this option enabled/disabled. It seems to break everything. https://imgur.com/a/OelohA1

**Comment by gcantoni** [comment]
`<item name="android:windowIsFloating">false</item>` did the trick to fix

**Comment by maxmpz** [comment]
It's generally not needed as none of Poweramp default styles has windowIsFloating=true, so no reason to set that to false.
I can't reproduce any issues on my devices, but if you can, please be more specific (device/ROM/Android version). Thanks!

**Comment by gcantoni** [comment]
Device: Pixel 3xl
ROM: stock aosp
Android Version: Android 9

Without that attribute all the UI as I have said completely broken.

**Comment by maxmpz** [comment]
I see, thanks for the details, but this is not reproducible for the sample skin with just transparent background tick checked. Again, there is no windowIsFloating anywhere, but if your skin is modified and includes something with windowIsFloating (basically that makes window to be a dialog), it can produce behavior you describing.

**Comment by gcantoni** [comment]
Yup. It's the main dashboard that has windowIsFloating.
