### ISSUE TITLE
Overriding settings style doesn't work

### ISSUE THREAD

**Issue by gcantoni** [maxmpz/powerampapi#24]
Hello Max,

According to `AndroidManifest` you are using `ActivityTheme_Settings(/Light/Dark) `for theming settings. In fact you are using as parent `@android:style/Theme.DeviceDefault.Settings` which is the default style included in framework in Android. 

Overriding it actually doesn't work. I don't know why honestly. It changes the main screen but it doesn't change the settings as desired.

This is how i'm doing it:
```
<style name="settings" parent="com.maxmpz.audioplayer:style/ActivityTheme_SettingsDark">
        <item name="android:statusBarColor">@color/colorSecondary</item>
        <item name="android:navigationBarColor">@color/colorSecondary</item>
        <item name="android:colorPrimary">@color/colorPrimaryDark</item>
        <item name="android:colorAccent">@color/defaultAccent</item>
    </style>
```

Any help would be very appreciated. thanks

**Comment by maxmpz** [comment]
Changing Settings theme via Skins is not possible at this time.

**Comment by gcantoni** [comment]
Are you able to make it possible?

**Comment by maxmpz** [comment]
Poweramp Settings are planned for refactoring - they will use PowerList, etc. custom views, so at this moment themeing them makes little sense anyway.

**Comment by gcantoni** [comment]
Sounds great! Thank you Max.
