### ISSUE TITLE
Completely transparent status bar

### ISSUE THREAD

**Issue by mixified** [maxmpz/powerampapi#26]
Hi Max, is there a way to make the status bar completely transparent? I tried with this code but it didn't work:
```
	<style name="trans_status">
		<item name="android:windowTranslucentStatus">true</item>
		<item name="android:statusBarColor">@android:color/transparent</item>
	</style>
```

I want to make that an option in the skin settings

Thanks!

**Comment by maxmpz** [comment]
Please see comments/attributes around this line: https://github.com/maxmpz/powerampapi/blob/master/poweramp_skin_sdk/reference_resources/values/default-styles.xml#L64

**Comment by mixified** [comment]
Sorry, I didn't noticed. Thanks Max
