### ISSUE TITLE
Lrc 

### ISSUE THREAD

**Issue by ghost** [maxmpz/powerampapi#28]
Feature requests.

Poweramp please when add LRC extension.

**Comment by maxmpz** [comment]
@ghost do you mean LRC API?

**Comment by Samysayu25** [comment]
Soy nuevo

**Comment by Samysayu25** [comment]
Quisiera descargar poweram última versión todo desbloqueado ilimitadamente

**Comment by dvdvideo1234** [comment]
@maxmpz 

When he said that I only understand ... https://en.wikipedia.org/wiki/RLC_circuit

**Comment by maxmpz** [comment]
Supported in builds 948+
