### ISSUE TITLE
Provider - playlist of provider tracks

### ISSUE THREAD

**Issue by MarkAdamson** [maxmpz/powerampapi#31]
Hi, I'm writing a custom provider for poweramp, and my source includes songs, as well as playlists of those songs. I'd like to be able to import the playlists along with the songs.

As far as I can tell, poweramp's provider API allows playlists of http streams, but doesn't allow playlists to reference songs elsewhere on the source - by documentids, or paths, or whatever.

Is this correct? Or am I missing something?

**Comment by maxmpz** [comment]
Hi. It's possible, but paths in the playlist should follow "parent_folder/file_name.ext" pattern. Poweramp uses just the (last) parent folder and file name to resolve playlist entry to the actual track/file.
The folder and file names come from Document.COLUMN_DISPLAY_NAME (for the appropriate folder or file). Note that if you don't provide COLUMN_DISPLAY_NAME, Poweramp will try to generate some path based on doc id, but that won't be stable, thus COLUMN_DISPLAY_NAME is recommended.

**Comment by MarkAdamson** [comment]
That works! Brilliant, thank you :)

Any chance of adding that to the documentation? I don't think it says it anywhere.

**Comment by maxmpz** [comment]
Thanks for the request - will do the update.

**Comment by MarkAdamson** [comment]
Awesome :)
