### ISSUE TITLE
Some more docs on *when* intents are sent would be pretty helpful

### ISSUE THREAD

**Issue by StratusFearMe21** [maxmpz/powerampapi#36]
It's so nice to be able to have a Hi-Res audiophile level audio player with this level of extensibility available on Android. Thanks for making a plugin system for it, and maintaining it (even if it's kinda unused). Your system is a breeze to work with, but it was very difficult to get started because of the lack of docs.

The docs describe *what* intents are sent to your plugin, but not *when* PowerAmp actually sends them. This is what I understand so far

- `PowerampAPI.ACTION_STATUS_CHANGED_EXPLICIT`
    - Sent when the player changes status for any reason (user initiated or automatic, such as playing when headphones are connected)
    - Sent when the user presses the :x: button in the notification
        - On this event, the player sends the paused state first
        - Then shortly after, the stopped state
    - Sent when the player starts back up after being in the stopped state
        - May be sent multiple times in this case
- `PowerampAPI.ACTION_TRACK_CHANGED_EXPLICIT`
    - Sent when the user manually changes the track in any way
    - Sent when the player finishes playing one track, and begins another
    - Sent when the player starts back up after being in the stopped state
        - May be sent multiple times in this case

- When the player sends the stopped state, you can unload PowerAmp related state from your app, since the next intents sent to your app will refresh it on everything it needs to know

**Comment by maxmpz** [comment]
The API allows both code based plugins/apps and automation tools, like Tasker, that's why it's intent based (mostly everything is intent messaging).
I added your detailed comments to the docs. Thanks for the feedback/update!
