### ISSUE TITLE
Poweramp inserts home videos into the playlist

### ISSUE THREAD

**Issue by dvdvideo1234** [maxmpz/powerampapi#43]
Hello,

Poweramp automatically inserts [Viber](https://www.viber.com) videos or audio recordings stored in the phone. How can I remove those from the playlist as I want to listen to music I can exclude home videos of the kids for example. How can I remove the added home videos without deleting them from the storage and prevent Poweramp to add them again?

**Comment by dvdvideo1234** [comment]
Never noticed PA has dedicaded location for searches including getting rid of home videos
![Uploading SmartSelectImage_2023-11-17-18-06-02-1.jpg…]()

**Comment by maxmpz** [comment]
Poweramp support forum is here: https://forum.powerampapp.com/
