### ISSUE TITLE
Folders unavailable on new android versions

### ISSUE THREAD

**Issue by dvdvideo1234** [maxmpz/powerampapi#45]
Hello

It seems the poweamp player is compatible with my Note4 with android 6.0 and not compatible with the car tablet on android 12 and Galaxy Ultra with android 14. It does not seem to find the folders with songs.
![Screenshot_20231217_145425_Poweramp](https://github.com/maxmpz/powerampapi/assets/9112662/ac00a598-2424-4809-b362-11e34a89eec1)

**Comment by dvdvideo1234** [comment]
Seems like there is a new way to enable the access so the phablet can read the folder. Click `Enable` then browse for folder.

**Comment by maxmpz** [comment]
The issue is unrelated to Poweramp API. You can report bugs/request help on official Poweramp forums here: https://powerampapp.com. Thanks!
