### ISSUE TITLE
Status on Album Art Loaders

### ISSUE THREAD

**Issue by kwyntes** [maxmpz/powerampapi#46]
Considering the README.md hasn't been updated in 2 years and it's the only place I've found any mention to Album Art Loaders, are there still plans for making such API or should I write a full track provider instead?

**Comment by maxmpz** [comment]
The https://github.com/maxmpz/powerampapi/blob/master/README.md file is just a TOC, underlying READMEs are updated more frequently.
As for Album Art APIs, the stub logic for the API is there, but there should be a feature request and/or some interest from users to continue with that. If you're developing some sort of plugin, the API can be enabled quickly for the next builds.
