### ISSUE TITLE
[Additional feature] Include a FFT display in the Poweramp player [ Android ]

### ISSUE THREAD

**Issue by dvdvideo1234** [maxmpz/powerampapi#5]
Hi,

Is there any chance that a FFT display should be included in the Poweramp player. It will be awesome
You can use one of my FFT algos: https://github.com/dvdvideo1234/MP3Toolbox/tree/master/functions/ffts

**Comment by packjustin79** [comment]
@dvdvideo1234 dvdvideo1234 changed the title from [Additional feature] Include a FFT display in Poweramp player to [Additional feature] Include a FFT display in the Poweramp player [ Android ] on Oct 30, 2015
@packjustin79
  
            
  [Additional feature] Include a FFT display in Poweramp player to [Additional feature] Include a FFT display in the Poweramp player [ Android ] on Oct 30, 2015
@packjustin79
  
            
 
Write

**Comment by packjustin79** [comment]
FFT display in Poweramp player
