### ISSUE TITLE
Sleep timer support

### ISSUE THREAD

**Issue by RavMahov** [maxmpz/powerampapi#6]
The API does not currently expose Sleep timer control

**Comment by mundane140** [comment]
If the API exposes the Pause and Play endpoints. You can easily implement a service on your own to act as a timer.
But that service would have to be controlled via another application if you want to edit it's working. I am doing something similar. I'll share details about my findings soon.

**Comment by maxmpz** [comment]
c59b727266c07aef79f25c4bbe8c1646a980dc21
