### ISSUE TITLE
ACTION_STATUS_CHANGED broadcast doesn't send as expected

### ISSUE THREAD

**Issue by lordfriend** [maxmpz/powerampapi#7]
Here is a method to reproduce this bug:

1. Select a playlist and play one of the track.
2. click Pause button to pause the player.
3. Quickly switch back to playlist and select another track. 

The new track is automatically played. This is not the problem.

But when you registered a broadcast receiver to receive the ACTION_STATUS_CHANGED broadcast, you will see at **step 2**,  the broadcast been received as expected, `status` is 1 (PowerampAPI.TRACK_PLAYING), and `paused` is true

But after you finish **step 3**, no broadcast is received. This is not the expected. A external plugin cannot figure out whether the track is being played or paused. because the pause state is changed but no more broadcast received.

**Comment by lordfriend** [comment]
This bug doesn't occur on Poweramp V3 beta.

**Comment by maxmpz** [comment]
Due to Poweramp v3 changes to the playing state handling, there is no more "status".
